// <auto-generated />
namespace DYEL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class fulltry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fulltry));
        
        string IMigrationMetadata.Id
        {
            get { return "201312160837048_full try"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
